apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../apps/echo/base

images:
  - name: ealen/echo-server
    newTag: "latest"

labels:
  - pairs:
      app.kubernetes.io/name: echo
      app.kubernetes.io/part-of: gitops-lab
      app.kubernetes.io/managed-by: kustomize
      environment: dev
    includeSelectors: false

configMapGenerator:
  - name: echo-config
    literals:
      - APP_ENV=dev
      - LOG_LEVEL=debug
      - APP_DEPLOY= argocd

patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: echo
    path: patch-ingress-host.yaml

replacements:
  - source:
      kind: Ingress
      name: echo
      fieldPath: spec.rules.0.host
    targets:
      - select:
          kind: Deployment
          name: echo
        fieldPaths:
          - spec.template.spec.containers.0.env.0.value