apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maximosnava/gitops-lab.git
    targetRevision: main
    path: environments/prod/echo
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true