apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../../apps/echo/base

patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: echo
    path: patch-ingress-host.yaml